language: node_js
node_js:
    - "4"
    - "6"
    - "8"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script: "npm run-script test-travis"
after_script: "npm install codecov.io && cat ./coverage/*/lcov.info | codecov"
