language: node_js
node_js:
  - "12"
dist: bionic
services:
  - xvfb
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
script: "npm run-script test-travis"
after_script: "npm install codecov.io && cat ./coverage/*/lcov.info | codecov"
